--- #YAML:1.0
name:               Acme-Debug
version:            1.48
abstract:           A handy module to identify lines of code where bugs may be found.
author:
    - Richard Foley <acme.debug@rfi.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
